### ISSUE TITLE
Does not work if the events-content text has li tags

### ISSUE THREAD

**Issue by amhanna86** [yCodeTech/horizontal-timeline-2.0#12]
**Describe the bug**
The timline crashes  if the text has `<li>` inside it

**Comment by yCodeTech** [comment]
Please can you give me some more details... I assume you are referring to the `events-content` text, is this correct? Have you had any issues with any other functionality of the timeline? What errors are you getting in the console?

Please could you also supply me with your code in the form of a codepen, so that I can exactly replicate the issue at hand.

**Comment by amhanna86** [comment]
Sorry my bug report was to short with no prober explanation. so the problem is when the event content had an li inside it the time line crashes giving this error :

`Uncaught TypeError: Cannot read property 'includes' of undefined
    at Function._create.eventDateDisplay (horizontal_timeline.2.0.min.js:11)
    at HTMLLIElement.<anonymous> (horizontal_timeline.2.0.min.js:11)
    at Function.each (jquery.min.js:2)
    at k.fn.init.each (jquery.min.js:2)
    at Function._create.date (horizontal_timeline.2.0.min.js:11)
    at r._create (horizontal_timeline.2.0.min.js:11)
    at r.init (horizontal_timeline.2.0.min.js:11)
    at new r (horizontal_timeline.2.0.min.js:11)
    at HTMLDivElement.<anonymous> (horizontal_timeline.2.0.min.js:11)
    at Function.each (jquery.min.js:2)`

because it is checking all the li exists in the page and founding one without the date attribute is crashing i found a solution by adding a class to the find function in the source code so it worked but caused another problem that the li not showing anymore  in the event content.

this is the codePen: https://codepen.io/AMhanna/pen/mdeEpzR

**Comment by yCodeTech** [comment]
After checking it out, I can confirm that you are correct, timeline is checking for any and all `<li>`'s existing in the timeline elements. I can see how this is problematic and I will create a patch so that it only looks for the list items with the data attribute.

I will push a patch out labelled as v2.0.5.2, hopefully by the end of Monday if no other testing errors occur. Thanks for your patience and continued use of the plugin.

**Comment by amhanna86** [comment]
Thank you and keep the good work its really useful and looks really good i would love to keep using it

**Comment by amhanna86** [comment]
Thanks for the fast update but there is still small issue that the li tag not showing in the event content any more i think this one is from css some how

**Comment by yCodeTech** [comment]
The reason the li won't show is similar to the original issue in that the CSS is also targeting the li without a data attribute, therefore hiding it. 

This was also fixed in the new version. Please can you make sure you are using the updated CSS file.

**Comment by amhanna86** [comment]
i did updated both files js and css i will double check and let you know the result
