### ISSUE TITLE
Throwing Error on empty content.

### ISSUE THREAD

**Issue by Loewe333** [yCodeTech/horizontal-timeline-2.0#14]
**Is your feature request related to a problem? Please describe.**
If there is no initial content (list items with data-horizontal-timeline attribute), the script is thowing an error: "There are no events at this point in time. Please add some content.". My timeline is nested into a js accordion, which gets broken after this "error". 

**Describe the solution you'd like**
My first idea: The mentioned scenario shouldn't thow an error, instead it should only display the error message in DOM.
Second idea: How about an additional option like "emptyTimelineText". This would be great for localization and custom project related output.

greetings =)

**Comment by yCodeTech** [comment]
Timeline has to have a minimum of one event, otherwise it's pointless creating the elements if there isn't any. That is why it has the error. (Granted, it isn't documented as such.)

Originally, timeline outputted the error as DOM only text, but it would continue running the script. Instead of changing the plugin to be inside one big `if` statement, I decided to allow timeline to throw an error if no events are found, which stops the whole script.

Unfortunately, I don't intend to change this error until I can find a more suitable way of 'exiting' the script.

I am unsure if it really needs an option to change the error text. It would be redundant as timeline shouldn't be empty anyway.

Is there a specific reason why you need an empty timeline? If so, please could you give me details about such scenarios.
