### ISSUE TITLE
Timeline is duplicated when using goTo method

### ISSUE THREAD

**Issue by ilariotr68** [yCodeTech/horizontal-timeline-2.0#19]
Hello, I have a problem with the timeline plugin, if I try to use the goTo object it duplicates my timeline, this is one of the examples provided to which I have added
the javascript code to jump directly to a certain date.
Anyone have an idea?
Thanks

```
<html>
<head>
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
	<link href="css/horizontal_timeline.2.0_v2.0.5.2.css" rel="stylesheet" type="text/css">
	<script src="js/horizontal_timeline.2.0_v2.0.5.3.js"></script>
</head>
<body>
<div class="horizontal-timeline" id="example">
	<div class="timeline">
		<div class="timeline-navigation" id="leftNav">
			<a href="" class="fas fa-3x fa-chevron-circle-left scroll-left inactive"></a>
			<a href="" class="fas fa-3x fa-arrow-circle-left prev inactive"></a>
		</div>
		<div class="events-wrapper touch-enabled">
			<div class="events" style="width: 717.5px; transform: translateX(0px);">
				<span class="filling-line" aria-hidden="true" style="transform: scaleX(0.0637863);"></span>
				<a href="" data-horizontal-timeline="{&quot;date&quot;: &quot;16/01/2014&quot;}" class="selected first" style="left: 0px; padding-left: 10px;">16/01/2014</a>
				<a href="" data-horizontal-timeline="{&quot;date&quot;: &quot;23/05/2015&quot;}" class="last" style="left: 400px;">23/05/2015</a>
			</div>
		</div>
		<div class="timeline-navigation" id="rightNav">
			<a href="" class="fas fa-3x fa-arrow-circle-right next"></a>
			<a href="" class="fas fa-3x fa-chevron-circle-right scroll-right inactive"></a>
		</div>
	</div>
	<div class="events-content">
		<ol>
			<li class="selected" data-horizontal-timeline='{"date": "16/01/2014"}'> // Event description here</li>
			<li data-horizontal-timeline='{"date": "23/05/2015"}'> // Event description here</li>
		</ol>
	</div>
</div> 
<script>
$('#example').horizontalTimeline({
	dateIntervals: {
		"desktop": 200,
		"tablet": 150,
		"mobile": 120,
		"minimal": false
	}
});
$('#example').horizontalTimeline('goTo', '23/05/2015');
</script>
</body>
</html>
```
![Immagine 2021-09-16 134243](https://user-images.githubusercontent.com/5508052/133606125-a903fba3-b232-43d6-a004-432838af2c02.png)

**Comment by yCodeTech** [comment]
Hi, thank you for using Horizontal Timeline 2.0! That is a very weird bug! I'll have a look into that and get back to you.

**Comment by yCodeTech** [comment]
I cannot recreate the bug as shown. However, it is possible that its related to a [known issue (issue 2)](https://github.com/yCodeTech/horizontal-timeline-2.0/blob/master/known-issues.md) where a method such as goTo can not be called straight after the initialisation code, as it would spit out errors because the JavaScript would read and process the method before the timeline code has chance to properly set up.

You have 2 choices... You can either wrap the method code in a `setTimeout` function with a delay of 300 or more, giving enough time for the plugin to set up. 

OR the recommended way of using the built-in attachable event `initialised.horizontalTimeline` which is fired after the plugin has been fully initialised/set up. See this [Codepen](https://codepen.io/ycodetech/pen/gORoBZN) for a full example.

Please let me know if this has fixed the issue, or if there's anything else I can help with.
