### ISSUE TITLE
Hidden li still maintains its height

### ISSUE THREAD

**Issue by pantelispanayiotou** [yCodeTech/horizontal-timeline-2.0#21]
First of all thank you for this great plugin!

I have a li that has more content than the previous divs. Somehow the tallest div maintains its height even if a li with much less content is selected, causing white space and content overflow. Am i using it wrong or is this a bug?

**Comment by pantelispanayiotou** [comment]
I found a workaround, i added an overflow: hidden on events-content div and it did it!

**Comment by yCodeTech** [comment]
Hi, I am glad you like the plugin!

I am struggling to recreate the issue, all my testing doesn't cause white space/content overflow. Could you please create your exact code in codepen or jsfiddle, where it shows the issue in action, so I can see what it's doing (or not doing). Also, if you could state what browser you are using too, that'll help with testing.
Thank you.

**Comment by pantelispanayiotou** [comment]
Hey, please have a look at: https://codesandbox.io/s/gallant-wildflower-gtobc?file=/index.html

The second item a lot of content, and you can see that on the first item it scrolls until it reaches the end of the second item. I solved it just by adding an overflow: hidden on events-content. I am using chrome

**Comment by yCodeTech** [comment]
Ah I see. Thanks for that.

Yes you could use `overflow: hidden`, or another alternative is to add `display: none` to all `.events-content li`, and add `display: block` to only the selected event via `.events-content li.selected`

See this [Codepen](https://codepen.io/ycodetech/pen/XWeKvrB)

However, when the scrollbar disappears, the timeline has a gap at the end. We can solve this by calling the refresh method on the timeline. To do this, we can use the event listeners `initialised.horizontalTimeline`  and `eventChanged.horizontalTimeline` to call the refresh on initialisation and also each time the event changes.
Though do we need to call refresh *every* time?? No. Only when there is no scrollbar.

So to check if there is a scrollbar, we can use a nice little script from [StackOverflow](https://stackoverflow.com/a/4814526/2358222). Then in the event listeners function, we can check to see if there is a scrollbar or not, if not then run refresh. Ah but then because of timing issues, we also need to use a `setTimeout` to ensure there is a delay before the checks takes place, just in case if there was a scrollbar but has just disappeared.

So altogether the JS would look like this:

```
// Check if element has scrollbar
// from https://stackoverflow.com/a/4814526/2358222
(function($) {
    $.fn.hasScrollBar = function() {
        // returns true if there's a `vertical` scrollbar, false otherwise..
        return this.get(0).scrollHeight > this.get(0).clientHeight;
    }
})(jQuery);

$("#example").horizontalTimeline();

$('#example').on("initialised.horizontalTimeline eventChanged.horizontalTimeline", function(event){
    setTimeout(function(){
        if($("html").hasScrollBar() === false) {
            $("#example").horizontalTimeline("refresh");
        }
    }, 500);
});
```

I will add this into the plugin for the next version.
I hope this helps.

**Comment by pantelispanayiotou** [comment]
Thank you for your detailed information! If you plan to release more features i 'd love to help!
