### ISSUE TITLE
Uncaught TypeError: this.init.addIdsAndClasses is not a function

### ISSUE THREAD

**Issue by xfwang03** [yCodeTech/horizontal-timeline-2.0#6]
Uncaught TypeError: this.init.addIdsAndClasses is not a function
    at r.refresh (horizontal_timeline.2.0.min.js:11)
    at r.addEvent (horizontal_timeline.2.0.min.js:11)
    at HTMLDivElement.<anonymous> (horizontal_timeline.2.0.min.js:11)
    at Function.each (jquery-3.3.1.js:354)
    at jQuery.fn.init.each (jquery-3.3.1.js:189)
    at jQuery.fn.init.e.fn.<computed> [as horizontalTimeline] (horizontal_timeline.2.0.min.js:11)

I am not sure if this is related any update of the library.

**Comment by yCodeTech** [comment]
Which version are you using?

It's quite possible that this refers to a [fix](https://github.com/yCodeTech/horizontal-timeline-2.0/blob/master/changelog.md#205-prerelease-31-v205-alpha31-and-311-v205-alpha311---05122019) that was released in version 2.0.5 Prerelease 3.1 [v2.0.5-alpha.3.1] and Prerelease 3.1.1 [v2.0.5-alpha.3.1.1] for the updated minified javascript.

If you are not using the latest version, I highly recommend you to update to the newly released major version 2.0.5 [v2.0.5] as this will give you all the bug fixes plus new additional content.

**Comment by yCodeTech** [comment]
I have not been able to replicate the issue in the newest version, and without any more information I can not determine the cause of the issue, other than what I have previously stated: I believe this to be the same issue in the 2.0.5 Pre-release 3 [v2.0.5-alpha.3] which was fixed in a later Pre-release. But it is highly recommended to update to the newest version. 

I will now close this issue. But please reopen it if the issue persists in the newest version and more information can be supplied.

**Comment by xfwang03** [comment]
thanks, @yCodeTech !
I was using 2.0.5 that is the version I saw issue in.
I rolled back to 2.0.4 and store it on my server instead of using cdn. the issue is gone now.
thanks again for maintaining this library. it is indeed awesome!

**Comment by xfwang03** [comment]
Regarding of the version, can you keep the minor version numbered in the version number?
For instance, something like: horizontal-timeline-2.0.5.min.js and horizontal-timeline-2.0.4.min.js etc.?

**Comment by yCodeTech** [comment]
Thanks for your further comments. I have tested the CDN file of the current version 2.0.5, that you saw the issue in, but I can not replicate any issues with Chrome, Firefox and Edge.

I take on board your suggestion of adding version numbers to the file name itself. I must admit that I didn't start adding the version number in the file until pre-release 3 (2.0.5-alpha.3), but then subsequently forgot to bump the version number up in the later patches, which I will make sure doesn't happen again.

<hr>

To enable me to grasp why and how your error occurred, please can you create a simple replicate of your scenario using jsfiddle, or similar, so that it replicates the error. Along with a link to this code or test page, please can you detail the steps you took before it gave the error, and if you could supply me with the browser you are using that would also be helpful.

I am concerned that 2.0.5 is giving you an error and doesn't for me, so any additional information would be helpful.
